package com.rknnovpn.panel.advisor

/**
 * Built-in package policy for apps that should stay outside RKNnoVPN even
 * when the rest of the device is proxied.
 */
object AlwaysDirectApps {
    private val exactPackages = setOf(
        "ru.oneme.app",
        "ru.fourpda.client",
        "ru.aliexpress.buyer",
        "ru.aviasales",
        "ru.burgerking",
        "ru.bestprice.fixprice",
        "ru.more.play",
        "ru.pepper",
        "ru.kfc.kfc_delivery",
        "com.apegroup.mcdonaldsrussia",
        "ru.rutube.app",
        "com.sevensky.app",
        "com.punicapp.whoosh",
        "ru.rt.video.app.mobile",
        "ru.gazprombank.android.mobilebank.app",
        "ru.letobank.Prometheus",
        "ru.dodopizza.app",
        "ru.ivi.client",
        "com.icemobile.lenta.prod",
        "ru.rzd.pass",
        "club.chizhik",
        "ru.yandex.searchplugin",
        "com.yandex.browser",
        "ru.yandex.browser",
        "ru.yandex.browser.lite",
        "ru.yandex.yandexmaps",
        "ru.yandex.maps",
        "ru.yandex.music",
        "com.vkontakte.android",
        "com.vk.im",
        "com.vk.mail",
        "com.vk.video",
        "com.vk.vkvideo",
        "com.uma.musicvk",
        "ru.vk.store",
        "ru.mail.mailapp",
        "ru.mail.cloud",
        "ru.ok.android",
        "ru.dublgis.dgismobile",
        "ru.dublgis.mobile",
        "ru.nspk.mirpay",
        "com.programmisty.emiasapp",
        "com.allgoritm.youla",
        "com.edadeal.android",
        "ru.foodfox.client",
        "ru.sbcs.store",
        "ru.vtb24.mobilebanking.android",
        "com.avito.android",
        "ru.ozon.app.android",
        "com.ozon.bank.android",
        "com.wildberries.ru",
        "ru.kinopoisk",
        "ru.kinopoisk.tv",
        "ru.megamarket.marketplace",
        "rtb.mobile.android",
        "ru.zen.android",
        "com.lamoda.lite",
        "ru.filit.mvideo.b2c",
        "ru.dns.shop.android",
        "ru.sportmaster.app",
        "ru.perekrestok.app",
        "ru.pyaterochka.app.browser",
        "ru.tander.magnit",
        "ru.vkusvill",
        "ru.beru.android",
        "ru.yandex.taxi",
        "ru.yandex.disk",
        "ru.yandex.mail",
        "ru.yandex.market",
        "ru.yandex.metro",
        "ru.yandex.weatherplugin",
        "ru.yandex.mobile.auth",
        "ru.sberbankmobile",
        "ru.sberbankmobile.arm",
        "ru.alfabank.mobile.android",
        "ru.tinkoff.android",
        "ru.tinkoff.investing",
        "com.idamob.tinkoff.android",
        "ru.raiffeisennews",
        "ru.rosbank.android",
        "ru.psbank.online",
        "ru.mts.bank",
        "ru.rostel",
        "ru.gosuslugi.pos",
        "ru.fns.lkfl",
        "ru.nalog.ibr",
        "ru.mos.app",
        "ru.mts.mymts",
        "com.beeline.dc",
        "ru.megafon.mlk",
        "ru.tele2.mytele2",
        "com.wireguard.android",
        "org.torproject.android",
        "org.torproject.torbrowser",
        "ch.protonvpn.android",
        "net.mullvad.mullvadvpn",
        "com.cloudflare.onedotonedotonedotone",
        "org.amnezia.vpn",
        "org.amnezia.awg",
        "app.hiddify.com",
        "ang.hiddify.com",
        "com.v2ray.ang",
        "com.v2raytun.android",
        "com.agn.v2ray",
        "com.happproxy",
        "io.nekohasekai.sfa",
        "io.nekohasekai.sagernet",
        "moe.nb4a",
        "org.outline.android.client",
        "net.openvpn.openvpn",
        "de.blinkt.openvpn",
        "com.github.shadowsocks",
        "com.getsurfboard",
        "com.github.kr328.clash",
        "com.github.metacubex.clash.meta",
        "com.notcvnt.rknhardering",
        "com.yourvpndead",
    )

    private val excludedPackages = setOf(
        "com.supercell.clashroyale",
    )

    private val prefixes = listOf(
        "ru.yandex.",
        "com.yandex.",
        "com.vk.",
        "ru.vk.",
        "ru.mail.",
        "com.mail.ru",
        "ru.ok.",
        "ru.dublgis.",
        "ru.nspk.",
        "com.programmisty.emiasapp",
        "com.allgoritm.youla",
        "com.edadeal.",
        "ru.foodfox.",
        "ru.sbcs.",
        "ru.ozon.",
        "com.ozon.",
        "com.wildberries.",
        "ru.wildberries.",
        "ru.kinopoisk",
        "ru.megamarket.",
        "rtb.mobile.android",
        "com.uma.musicvk",
        "ru.vk.store",
        "ru.zen.",
        "com.lamoda.",
        "ru.filit.mvideo.",
        "ru.dns.shop.",
        "ru.sportmaster.",
        "ru.perekrestok.",
        "ru.pyaterochka.",
        "ru.tander.magnit",
        "ru.vkusvill",
        "ru.vtb",
        "ru.sber",
        "ru.alfabank",
        "ru.tinkoff",
        "com.idamob.tinkoff",
        "ru.raiffeisen",
        "ru.rosbank",
        "ru.psbank",
        "ru.mts.bank",
        "ru.gosuslugi",
        "ru.fns",
        "ru.nalog",
        "ru.mos",
        "com.avito",
        "ru.ozon",
        "com.wildberries",
        "org.amnezia.",
        "app.hiddify.",
        "ang.hiddify.",
        "com.v2ray.",
        "com.v2raytun.",
        "com.happproxy",
    )

    private val keywords = listOf(
        "vpn",
        "proxy",
        "v2ray",
        "xray",
        "hiddify",
        "nekobox",
        "nekoray",
        "amnezia",
        "wireguard",
        "outline",
        "openvpn",
        "shadowsocks",
        "clash",
        "singbox",
        "sing-box",
        "sagernet",
        "tun2socks",
    )

    fun matches(
        packageName: String,
        manualPackages: Set<String> = emptySet(),
        excludedPackages: Set<String> = emptySet(),
    ): Boolean {
        if (packageName in manualPackages) return true
        if (packageName in excludedPackages) return false
        if (packageName in exactPackages) return true
        if (prefixes.any(packageName::startsWith)) return true
        val lower = packageName.lowercase()
        return keywords.any(lower::contains)
    }
}
