package com.rknnovpn.panel.ipc

// Generated from daemon/internal/ipc/contract_manifest.json.
// Run .github/scripts/check_ipc_contract_codegen.py --write after editing the IPC contract.
internal object GeneratedDaemonContract {
    const val CONTRACT_VERSION: Int = 3
    data class OperationPolicy(
        val stages: List<String>,
        val errorCodes: List<String>,
    )
    val ERROR_CODES: List<String> = listOf("INVALID_PARAMS", "INTERNAL_ERROR", "CONFIG_ERROR", "RUNTIME_BUSY", "RESET_IN_PROGRESS")
    val COMPATIBILITY_POLICIES: Set<String> = setOf("release-mismatch-allowed", "requires-schema", "requires-runtime-schema")
    val OPERATION_POLICIES: Map<String, OperationPolicy> = mapOf(
        "applyDesiredState" to OperationPolicy(
            stages = listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
            errorCodes = listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        ),
        "config-mutation" to OperationPolicy(
            stages = listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
            errorCodes = listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        ),
        "profile-apply" to OperationPolicy(
            stages = listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
            errorCodes = listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        ),
        "reset" to OperationPolicy(
            stages = listOf("accepted", "activeOperation", "lastOperation"),
            errorCodes = listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        ),
        "restart" to OperationPolicy(
            stages = listOf("accepted", "activeOperation", "lastOperation"),
            errorCodes = listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        ),
        "start" to OperationPolicy(
            stages = listOf("accepted", "activeOperation", "lastOperation"),
            errorCodes = listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        ),
        "stop" to OperationPolicy(
            stages = listOf("accepted", "activeOperation", "lastOperation"),
            errorCodes = listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        ),
        "update-download" to OperationPolicy(
            stages = listOf("update-check", "update-download", "update-verify", "persist-artifacts"),
            errorCodes = listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "INTERNAL_ERROR"),
        ),
        "update-install" to OperationPolicy(
            stages = listOf("accepted", "activeOperation", "lastOperation"),
            errorCodes = listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        ),
    )
    val APK_REQUIRED_METHODS: Set<String> = setOf(
        "app.list",
        "app.resolveUid",
        "audit",
        "backend.applyDesiredState",
        "backend.reset",
        "backend.restart",
        "backend.start",
        "backend.status",
        "backend.stop",
        "compat.check",
        "config-list",
        "diagnostics.health",
        "diagnostics.report",
        "diagnostics.testNodes",
        "ipc.contract",
        "logs",
        "profile.apply",
        "profile.commitImportBatch",
        "profile.dns.patch",
        "profile.get",
        "profile.importNodes",
        "profile.importNodesBatch",
        "profile.inbound.patch",
        "profile.node.remove",
        "profile.node.upsert",
        "profile.patch",
        "profile.routing.patch",
        "profile.setActiveNode",
        "self-check",
        "subscription.preview",
        "subscription.refresh",
        "update-check",
        "update-download",
        "update-install",
        "version",
    )
    val METHOD_CAPABILITIES: Map<String, String> = mapOf(
        "app.list" to "privacy.audit.v2",
        "app.resolveUid" to "privacy.audit.v2",
        "audit" to "privacy.audit.v2",
        "backend.applyDesiredState" to "runtime.v2",
        "backend.reset" to "backend.reset.structured",
        "backend.restart" to "runtime.v2",
        "backend.start" to "runtime.v2",
        "backend.status" to "runtime.v2",
        "backend.stop" to "runtime.v2",
        "compat.check" to "ipc.contract.v1",
        "config-import" to "config.import.v2",
        "config-list" to "config.schema.v5",
        "diagnostics.health" to "diagnostics.health.v2",
        "diagnostics.report" to "diagnostics.bundle.v2",
        "diagnostics.testNodes" to "diagnostics.testNodes.v2",
        "ipc.contract" to "ipc.contract.v1",
        "logs" to "runtime.logs",
        "profile.apply" to "profile.apply.v2",
        "profile.commitImportBatch" to "profile.importNodes.v2",
        "profile.dns.patch" to "profile.patch.v1",
        "profile.get" to "profile.document.v2",
        "profile.importNodes" to "profile.importNodes.v2",
        "profile.importNodesBatch" to "profile.importNodes.v2",
        "profile.inbound.patch" to "profile.patch.v1",
        "profile.node.remove" to "profile.patch.v1",
        "profile.node.upsert" to "profile.patch.v1",
        "profile.patch" to "profile.patch.v1",
        "profile.routing.patch" to "profile.patch.v1",
        "profile.setActiveNode" to "profile.apply.v2",
        "self-check" to "privacy.self-check.v1",
        "subscription.preview" to "profile.subscription.v2",
        "subscription.refresh" to "profile.subscription.v2",
        "update-check" to "update.install.v1",
        "update-download" to "update.install.v1",
        "update-install" to "update.install.v1",
        "version" to "ipc.contract.v1",
    )
    val MUTATING_METHODS: Set<String> = setOf(
        "backend.applyDesiredState",
        "backend.reset",
        "backend.restart",
        "backend.start",
        "backend.stop",
        "config-import",
        "profile.apply",
        "profile.commitImportBatch",
        "profile.dns.patch",
        "profile.importNodes",
        "profile.inbound.patch",
        "profile.node.remove",
        "profile.node.upsert",
        "profile.patch",
        "profile.routing.patch",
        "profile.setActiveNode",
        "subscription.refresh",
        "update-download",
        "update-install",
    )
    val ASYNC_METHODS: Set<String> = setOf(
        "backend.reset",
        "backend.restart",
        "backend.start",
        "backend.stop",
        "config-import",
        "profile.apply",
        "profile.commitImportBatch",
        "profile.dns.patch",
        "profile.importNodes",
        "profile.inbound.patch",
        "profile.node.remove",
        "profile.node.upsert",
        "profile.patch",
        "profile.routing.patch",
        "profile.setActiveNode",
        "subscription.refresh",
        "update-install",
    )
    val METHOD_REQUESTS: Map<String, String> = mapOf(
        "app.list" to "empty",
        "app.resolveUid" to "ResolveUidRequest",
        "audit" to "empty",
        "backend.applyDesiredState" to "DesiredState",
        "backend.reset" to "empty",
        "backend.restart" to "empty",
        "backend.start" to "empty",
        "backend.status" to "BackendStatusRequest",
        "backend.stop" to "empty",
        "compat.check" to "CompatibilityCheckRequest",
        "config-import" to "Config",
        "config-list" to "empty",
        "diagnostics.health" to "empty",
        "diagnostics.report" to "DiagnosticsReportRequest",
        "diagnostics.testNodes" to "TestNodesRequest",
        "ipc.contract" to "empty",
        "logs" to "LogsRequest",
        "profile.apply" to "ProfileApplyRequest|ProfileDocument",
        "profile.commitImportBatch" to "CommitImportBatchRequest",
        "profile.dns.patch" to "DNSPatchRequest",
        "profile.get" to "empty",
        "profile.importNodes" to "ImportNodesRequest",
        "profile.importNodesBatch" to "ImportNodesBatchRequest",
        "profile.inbound.patch" to "InboundPatchRequest",
        "profile.node.remove" to "NodeRemoveRequest",
        "profile.node.upsert" to "NodeUpsertRequest",
        "profile.patch" to "ProfilePatchRequest",
        "profile.routing.patch" to "RoutingPatchRequest",
        "profile.setActiveNode" to "SetActiveNodeRequest",
        "self-check" to "SelfCheckRequest",
        "subscription.preview" to "SubscriptionURLRequest",
        "subscription.refresh" to "SubscriptionURLRequest",
        "update-check" to "empty",
        "update-download" to "empty",
        "update-install" to "UpdateInstallRequest",
        "version" to "empty",
    )
    val METHOD_RESULTS: Map<String, String> = mapOf(
        "app.list" to "InstalledApp[]",
        "app.resolveUid" to "ResolveUidResult",
        "audit" to "AuditReport",
        "backend.applyDesiredState" to "BackendStatusV2",
        "backend.reset" to "AcceptedStatus",
        "backend.restart" to "AcceptedStatus",
        "backend.start" to "AcceptedStatus",
        "backend.status" to "BackendStatusV2",
        "backend.stop" to "AcceptedStatus",
        "compat.check" to "CompatibilityCheckResult",
        "config-import" to "ConfigMutationResult",
        "config-list" to "ConfigKeyTypes",
        "diagnostics.health" to "HealthSnapshot",
        "diagnostics.report" to "DiagnosticsReport",
        "diagnostics.testNodes" to "NodeProbeResult[]",
        "ipc.contract" to "IPCContract",
        "logs" to "LogSection[]",
        "profile.apply" to "ProfileApplyResult",
        "profile.commitImportBatch" to "ProfileApplyResult",
        "profile.dns.patch" to "ProfileApplyResult",
        "profile.get" to "ProfileDocument",
        "profile.importNodes" to "ProfileApplyResult",
        "profile.importNodesBatch" to "ImportNodesBatchResult",
        "profile.inbound.patch" to "ProfileApplyResult",
        "profile.node.remove" to "ProfileApplyResult",
        "profile.node.upsert" to "ProfileApplyResult",
        "profile.patch" to "ProfileApplyResult",
        "profile.routing.patch" to "ProfileApplyResult",
        "profile.setActiveNode" to "ProfileApplyResult",
        "self-check" to "SelfCheckReport",
        "subscription.preview" to "SubscriptionPreview",
        "subscription.refresh" to "SubscriptionRefreshResult",
        "update-check" to "UpdateInfo",
        "update-download" to "UpdateArtifactSet",
        "update-install" to "AcceptedStatus",
        "version" to "VersionInfo",
    )
    val METHOD_ERROR_CODES: Map<String, List<String>> = mapOf(
        "app.list" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "app.resolveUid" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "audit" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "backend.applyDesiredState" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "backend.reset" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "backend.restart" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "backend.start" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "backend.status" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "backend.stop" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "compat.check" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "config-import" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "config-list" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "diagnostics.health" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "diagnostics.report" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "diagnostics.testNodes" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "ipc.contract" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "logs" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "profile.apply" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "profile.commitImportBatch" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "profile.dns.patch" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "profile.get" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "profile.importNodes" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "profile.importNodesBatch" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "profile.inbound.patch" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "profile.node.remove" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "profile.node.upsert" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "profile.patch" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "profile.routing.patch" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "profile.setActiveNode" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "self-check" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "subscription.preview" to listOf("INVALID_PARAMS", "INTERNAL_ERROR", "CONFIG_ERROR"),
        "subscription.refresh" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "update-check" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
        "update-download" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "INTERNAL_ERROR"),
        "update-install" to listOf("INVALID_PARAMS", "RUNTIME_BUSY", "RESET_IN_PROGRESS", "CONFIG_ERROR", "INTERNAL_ERROR"),
        "version" to listOf("INVALID_PARAMS", "INTERNAL_ERROR"),
    )
    val METHOD_COMPATIBILITY: Map<String, String> = mapOf(
        "app.list" to "",
        "app.resolveUid" to "",
        "audit" to "",
        "backend.applyDesiredState" to "requires-schema",
        "backend.reset" to "release-mismatch-allowed",
        "backend.restart" to "requires-runtime-schema",
        "backend.start" to "requires-runtime-schema",
        "backend.status" to "",
        "backend.stop" to "release-mismatch-allowed",
        "compat.check" to "",
        "config-import" to "requires-schema",
        "config-list" to "",
        "diagnostics.health" to "",
        "diagnostics.report" to "release-mismatch-allowed",
        "diagnostics.testNodes" to "",
        "ipc.contract" to "",
        "logs" to "release-mismatch-allowed",
        "profile.apply" to "requires-schema",
        "profile.commitImportBatch" to "requires-schema",
        "profile.dns.patch" to "requires-schema",
        "profile.get" to "",
        "profile.importNodes" to "requires-schema",
        "profile.importNodesBatch" to "",
        "profile.inbound.patch" to "requires-schema",
        "profile.node.remove" to "requires-schema",
        "profile.node.upsert" to "requires-schema",
        "profile.patch" to "requires-schema",
        "profile.routing.patch" to "requires-schema",
        "profile.setActiveNode" to "requires-schema",
        "self-check" to "release-mismatch-allowed",
        "subscription.preview" to "",
        "subscription.refresh" to "requires-schema",
        "update-check" to "release-mismatch-allowed",
        "update-download" to "release-mismatch-allowed",
        "update-install" to "release-mismatch-allowed",
        "version" to "",
    )
    val OPERATION_TYPES: Map<String, String> = mapOf(
        "backend.applyDesiredState" to "applyDesiredState",
        "backend.reset" to "reset",
        "backend.restart" to "restart",
        "backend.start" to "start",
        "backend.stop" to "stop",
        "config-import" to "config-mutation",
        "profile.apply" to "profile-apply",
        "profile.commitImportBatch" to "profile-apply",
        "profile.dns.patch" to "profile-apply",
        "profile.importNodes" to "profile-apply",
        "profile.inbound.patch" to "profile-apply",
        "profile.node.remove" to "profile-apply",
        "profile.node.upsert" to "profile-apply",
        "profile.patch" to "profile-apply",
        "profile.routing.patch" to "profile-apply",
        "profile.setActiveNode" to "profile-apply",
        "subscription.refresh" to "profile-apply",
        "update-download" to "update-download",
        "update-install" to "update-install",
    )
    val OPERATION_ASYNC_RESULT_VIA: Map<String, String> = mapOf(
        "backend.applyDesiredState" to "",
        "backend.reset" to "backend.status.lastOperation",
        "backend.restart" to "backend.status.lastOperation",
        "backend.start" to "backend.status.lastOperation",
        "backend.stop" to "backend.status.lastOperation",
        "config-import" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.apply" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.commitImportBatch" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.dns.patch" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.importNodes" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.inbound.patch" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.node.remove" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.node.upsert" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.patch" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.routing.patch" to "backend.status.activeOperation|backend.status.lastOperation",
        "profile.setActiveNode" to "backend.status.activeOperation|backend.status.lastOperation",
        "subscription.refresh" to "backend.status.activeOperation|backend.status.lastOperation",
        "update-download" to "",
        "update-install" to "backend.status.lastOperation",
    )
    val OPERATION_STAGES: Map<String, List<String>> = mapOf(
        "backend.applyDesiredState" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "backend.reset" to listOf("accepted", "activeOperation", "lastOperation"),
        "backend.restart" to listOf("accepted", "activeOperation", "lastOperation"),
        "backend.start" to listOf("accepted", "activeOperation", "lastOperation"),
        "backend.stop" to listOf("accepted", "activeOperation", "lastOperation"),
        "config-import" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.apply" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.commitImportBatch" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.dns.patch" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.importNodes" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.inbound.patch" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.node.remove" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.node.upsert" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.patch" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.routing.patch" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "profile.setActiveNode" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "subscription.refresh" to listOf("validate", "render", "runtime-idle", "persist-draft", "runtime-apply", "verify", "commit-generation", "cleanup"),
        "update-download" to listOf("update-check", "update-download", "update-verify", "persist-artifacts"),
        "update-install" to listOf("accepted", "activeOperation", "lastOperation"),
    )
}
